/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tx.nodes

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun test1() {
        // TODO: implement tests
    }
}
